export const API_ROUTES = {
  session: "session",
  login: "login",
  logout: "logout",
  events: "events",
  devices: "devices",
  lastPositions: "positions/last",
  finance: "finance",
  driverBehavior: "driver-behavior",
  maintenance: "maintenance",
  fuel: "reports/fuel",
  routing: "routing",
  routes: "euro/routes",
  itineraries: "itineraries",
  compliance: "compliance",
  iotSensors: "iot-sensors",
  videoTelematics: "video-telematics",
  positionsExport: "positions/export",
  eventResolve: (id) => `events/${id}/resolve`,
  reports: {
    trips: "traccar/reports/trips",
    stops: "traccar/reports/stops",
    summary: "traccar/reports/summary",
    route: "traccar/reports/route",
    positions: "reports/positions",
    analytic: "reports/analytic",
    positionsPdf: "reports/positions/pdf",
    positionsXlsx: "reports/positions/xlsx",
    positionsCsv: "reports/positions/csv",
  },
  commands: "commands",
  commandsHistory: "commands/history",
  commandsHistoryStatus: "commands/history/status",
  commandsSend: "commands/send",
  commandsSendSms: "commands/send-sms",
  commandsTypes: "commands/types",
  commandsCustom: "commands/custom",
  notifications: "notifications",
  groups: "groups",
  userPreferences: "user/preferences",
  analytics: {
    eventsHeatmap: "events/heatmap",
  },
  clients: "clients",
  users: "users",
  geofenceGroups: "geofence-groups",
  models: "models",
  geofences: "geofences",
  drivers: "drivers",
  homeCriticalVehicles: "home/critical-vehicles",
  media: {
    faceAlerts: "media/face/alerts",
  },
  core: {
    base: "core",
    models: "core/models",
    devices: "core/devices",
    importDevices: "core/devices/import",
    syncDevices: "core/devices/sync",
    chips: "core/chips",
    vehicles: "core/vehicles",
    telemetry: "core/telemetry",
    stock: "core/stock",
    vehicleTraccarDevice: (vehicleId) => `core/vehicles/${vehicleId}/traccar-device`,
  },
  crm: {
    base: "crm",
    clients: "clients",
    alerts: "alerts",
    contacts: (clientId) => `clients/${clientId}/contacts`,
    tags: "tags",
    pipeline: "pipeline",
    deals: "deals",
    activities: "activities",
    reminders: "reminders",
  },
  health: "health",
  traccarHealth: "health/traccar",
  traccar: {
    events: "traccar/events",
    groups: "traccar/groups",
    reports: {
      trips: "traccar/reports/trips",
      route: "traccar/reports/route",
      stops: "traccar/reports/stops",
      summary: "traccar/reports/summary",
    },
  },
  mapMatching: "map-matching",
  mapRoute: "map-route",
  protocols: "protocols",
  protocolEvents: (protocol) => `protocols/${protocol}/events`,
  protocolEventSeverity: (protocol) => `protocols/${protocol}/events/severity`,
  protocolCommands: (protocol) => `protocols/${protocol}/commands`,
  tracker: {
    devices: "tracker/devices",
    mappings: "tracker/mappings",
    telemetryMappings: "tracker/mappings/telemetry",
    eventMappings: "tracker/mappings/events",
  },
};

export default API_ROUTES;
