export const API_ROUTES = {
  session: "session",
  login: "login",
  logout: "logout",
  events: "events",
  lastPositions: "positions/last",
  finance: "finance",
  driverBehavior: "driver-behavior",
  maintenance: "maintenance",
  fuel: "reports/fuel",
  routing: "routing",
  compliance: "compliance",
  iotSensors: "iot-sensors",
  videoTelematics: "video-telematics",
  positionsExport: "positions/export",
  reports: {
    trips: "traccar/reports/trips",
    stops: "traccar/reports/stops",
    summary: "traccar/reports/summary",
    route: "traccar/reports/route",
  },
  commands: "commands",
  notifications: "notifications",
  groups: "groups",
  userPreferences: "user/preferences",
  analytics: {
    eventsHeatmap: "events/heatmap",
  },
  clients: "clients",
  users: "users",
  geofenceGroups: "geofence-groups",
  models: "models",
  geofences: "geofences",
  drivers: "drivers",
  media: {
    faceAlerts: "media/face/alerts",
  },
  core: {
    base: "core",
    models: "core/models",
    devices: "core/devices",
    importDevices: "core/devices/import",
    chips: "core/chips",
    vehicles: "core/vehicles",
    telemetry: "core/telemetry",
    stock: "core/stock",
  },
  crm: {
    base: "crm",
    clients: "clients",
    alerts: "alerts",
    contacts: (clientId) => `clients/${clientId}/contacts`,
    tags: "tags",
    pipeline: "pipeline",
    deals: "deals",
    activities: "activities",
    reminders: "reminders",
  },
  health: "health",
  traccarHealth: "health/traccar",
  traccar: {
    events: "traccar/events",
    reports: {
      trips: "traccar/reports/trips",
      route: "traccar/reports/route",
      stops: "traccar/reports/stops",
      summary: "traccar/reports/summary",
    },
  },
};

export default API_ROUTES;
