-- Add extended vehicle detail fields
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "item" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "identifier" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "chassis" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "renavam" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "color" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "modelYear" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "manufactureYear" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "fipeCode" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "fipeValue" DOUBLE PRECISION;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "zeroKm" BOOLEAN NOT NULL DEFAULT false;
