ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "assignedTechnicianId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "schedulingId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "workOrderId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "vehicleBrand" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "vehicleYear" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "vehicleColor" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "selectedEquipments" JSONB;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "isRescheduled" BOOLEAN DEFAULT false;
