CREATE TABLE IF NOT EXISTS trust_center_user_access (
  id VARCHAR(36) PRIMARY KEY,
  client_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NULL,
  user_name VARCHAR(255) NOT NULL,
  profile VARCHAR(64) NULL,
  vehicle_id VARCHAR(64) NULL,
  vehicle_label VARCHAR(255) NULL,
  device_id VARCHAR(64) NULL,
  esp32_device VARCHAR(255) NULL,
  state VARCHAR(32) NOT NULL,
  challenge VARCHAR(64) NULL,
  validation_method VARCHAR(64) NULL,
  result VARCHAR(64) NULL,
  action_type VARCHAR(64) NULL,
  access_password_hash VARCHAR(128) NOT NULL,
  access_password_salt VARCHAR(64) NOT NULL,
  access_password_masked VARCHAR(32) NULL,
  last_heartbeat_at TIMESTAMP NULL,
  last_attempt_at TIMESTAMP NULL,
  last_access_at TIMESTAMP NULL,
  created_by VARCHAR(64) NULL,
  used_by VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trust_center_activity (
  id VARCHAR(36) PRIMARY KEY,
  client_id VARCHAR(64) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  user_id VARCHAR(64) NULL,
  user_name VARCHAR(255) NULL,
  profile VARCHAR(64) NULL,
  vehicle_id VARCHAR(64) NULL,
  vehicle_label VARCHAR(255) NULL,
  device_id VARCHAR(64) NULL,
  device_label VARCHAR(255) NULL,
  method VARCHAR(64) NULL,
  action VARCHAR(128) NOT NULL,
  result VARCHAR(64) NULL,
  action_type VARCHAR(64) NULL,
  esp32_payload JSON NULL,
  created_by VARCHAR(64) NULL,
  used_by VARCHAR(64) NULL,
  details JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trust_center_counter_key (
  id VARCHAR(36) PRIMARY KEY,
  client_id VARCHAR(64) NOT NULL,
  target_user_id VARCHAR(64) NULL,
  target_user_name VARCHAR(255) NULL,
  vehicle_id VARCHAR(64) NULL,
  vehicle_label VARCHAR(255) NULL,
  device_id VARCHAR(64) NULL,
  device_label VARCHAR(255) NULL,
  challenge VARCHAR(64) NOT NULL,
  counter_key VARCHAR(32) NOT NULL,
  base_password_hash VARCHAR(128) NOT NULL,
  base_password_salt VARCHAR(64) NOT NULL,
  base_password_masked VARCHAR(32) NULL,
  status VARCHAR(32) NOT NULL,
  uses_count INT NOT NULL DEFAULT 0,
  max_uses INT NOT NULL DEFAULT 1,
  first_used_at TIMESTAMP NULL,
  last_used_at TIMESTAMP NULL,
  used_by VARCHAR(64) NULL,
  created_by VARCHAR(64) NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trust_center_audit (
  id VARCHAR(36) PRIMARY KEY,
  client_id VARCHAR(64) NOT NULL,
  action VARCHAR(128) NOT NULL,
  result VARCHAR(64) NOT NULL,
  actor_id VARCHAR(64) NULL,
  actor_name VARCHAR(255) NULL,
  user_id VARCHAR(64) NULL,
  vehicle_id VARCHAR(64) NULL,
  device_id VARCHAR(64) NULL,
  details JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
