export const positionsColumns = [
  { key: "gpsTime", labelPt: "Hora GPS", labelPdf: "Hora GPS", width: 140, defaultVisible: true, weight: 1.4 },
  { key: "address", labelPt: "Endereço", labelPdf: "Endereço", width: 260, defaultVisible: true, weight: 2.6 },
  { key: "speed", labelPt: "Velocidade", labelPdf: "Velocidade", width: 90, defaultVisible: true, weight: 0.9 },
  { key: "ignition", labelPt: "Ignição", labelPdf: "Ignição", width: 90, defaultVisible: true, weight: 0.9 },
  { key: "vehicleState", labelPt: "Movimento", labelPdf: "Movimento", width: 130, defaultVisible: true, weight: 1.3 },
  { key: "distance", labelPt: "Distância (km)", labelPdf: "Distância (km)", width: 110, defaultVisible: true, weight: 1 },
  { key: "totalDistance", labelPt: "Distância Total (km)", labelPdf: "Distância Total (km)", width: 140, defaultVisible: true, weight: 1.2 },
  { key: "vehicleVoltage", labelPt: "Tensão do Veículo (V)", labelPdf: "Tensão do Veículo (V)", width: 150, defaultVisible: true, weight: 1.3 },
  { key: "batteryLevel", labelPt: "Nível de Bateria (%)", labelPdf: "Nível de Bateria (%)", width: 140, defaultVisible: true, weight: 1.2 },
  { key: "digitalInput1", labelPt: "Entrada 1", labelPdf: "Entrada 1", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput2", labelPt: "Entrada 2", labelPdf: "Entrada 2", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput3", labelPt: "Entrada 3", labelPdf: "Entrada 3", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput4", labelPt: "Entrada 4", labelPdf: "Entrada 4", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput5", labelPt: "Entrada 5", labelPdf: "Entrada 5", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput6", labelPt: "Entrada 6", labelPdf: "Entrada 6", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput7", labelPt: "Entrada 7", labelPdf: "Entrada 7", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalInput8", labelPt: "Entrada 8", labelPdf: "Entrada 8", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput1", labelPt: "Saída 1", labelPdf: "Saída 1", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput2", labelPt: "Saída 2", labelPdf: "Saída 2", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput3", labelPt: "Saída 3", labelPdf: "Saída 3", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput4", labelPt: "Saída 4", labelPdf: "Saída 4", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput5", labelPt: "Saída 5", labelPdf: "Saída 5", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput6", labelPt: "Saída 6", labelPdf: "Saída 6", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput7", labelPt: "Saída 7", labelPdf: "Saída 7", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "digitalOutput8", labelPt: "Saída 8", labelPdf: "Saída 8", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "satellites", labelPt: "Satélites", labelPdf: "Satélites", width: 90, defaultVisible: false, weight: 0.9 },
  { key: "hdop", labelPt: "HDOP", labelPdf: "HDOP", width: 90, defaultVisible: false, weight: 0.9 },
  { key: "accuracy", labelPt: "Precisão (m)", labelPdf: "Precisão (m)", width: 100, defaultVisible: false, weight: 1 },
  { key: "rssi", labelPt: "RSSI", labelPdf: "RSSI", width: 80, defaultVisible: false, weight: 0.8 },
  { key: "geofence", labelPt: "Cerca Virtual", labelPdf: "Cerca Virtual", width: 140, defaultVisible: false, weight: 1.2 },
  { key: "deviceTemp", labelPt: "Temperatura do Dispositivo (°C)", labelPdf: "Temperatura do Dispositivo (°C)", width: 160, defaultVisible: false, weight: 1.4 },
  { key: "handBrake", labelPt: "Freio de Mão", labelPdf: "Freio de Mão", width: 130, defaultVisible: false, weight: 1.1 },
  { key: "ioDetails", labelPt: "Detalhes (IO)", labelPdf: "Detalhes (IO)", width: 220, defaultVisible: false, weight: 2.2 },
  { key: "commandResponse", labelPt: "Resposta do Comando", labelPdf: "Resposta do Comando", width: 220, defaultVisible: true, weight: 2.2 },
  {
    key: "deviceStatus",
    labelPt: "Status do Equipamento",
    labelPdf: "Status do Equipamento",
    width: 180,
    defaultVisible: true,
    weight: 1.6,
  },
  {
    key: "deviceStatusEvent",
    labelPt: "Transição de Status",
    labelPdf: "Transição de Status",
    width: 200,
    defaultVisible: true,
    weight: 1.8,
  },
  { key: "deviceTime", labelPt: "Hora do Dispositivo", labelPdf: "Hora do Dispositivo", width: 140, defaultVisible: false, weight: 1.4 },
  { key: "serverTime", labelPt: "Hora do Servidor", labelPdf: "Hora do Servidor", width: 140, defaultVisible: false, weight: 1.4 },
  { key: "latitude", labelPt: "Latitude", labelPdf: "Latitude", width: 110, defaultVisible: false, weight: 1 },
  { key: "longitude", labelPt: "Longitude", labelPdf: "Longitude", width: 110, defaultVisible: false, weight: 1 },
  { key: "direction", labelPt: "Direção", labelPdf: "Direção", width: 90, defaultVisible: false, weight: 0.9 },
];

export const positionsColumnMap = new Map(positionsColumns.map((column) => [column.key, column]));

export function resolveColumnLabel(column, variant = "pt") {
  if (!column) return "[SEM TRADUÇÃO]";
  const label = variant === "pdf" ? column.labelPdf : column.labelPt;
  return label || `[SEM TRADUÇÃO] ${column.key}`;
}
